"""Validation of short-rate calibration (numerical-validation skill).

The headline is the exact-fit-vs-best-fit contrast: calibrated to the same curve, **Hull--White
reproduces the term structure exactly** (its time-dependent drift absorbs the whole curve),
while **Vasicek and CIR leave a residual** — the concrete reason practitioners use Hull--White
for anything that must be arbitrage-free to the current curve. A known-truth check pins the
calibrator: a curve *generated by* a Vasicek model is recovered by Vasicek calibration to
essentially zero residual.
"""

from __future__ import annotations

import numpy as np
from quantica.rates import (
    CIR,
    Deposit,
    DiscountCurve,
    HullWhite,
    Swap,
    Vasicek,
    bootstrap,
    calibrate_cir,
    calibrate_vasicek,
    log_linear_discount,
    monotone_cubic_zero,
)


def _market_curve() -> DiscountCurve:
    market = [
        Deposit(0.25, 0.030),
        Deposit(0.5, 0.032),
        Deposit(1.0, 0.035),
        Swap(2, 0.037),
        Swap(3, 0.039),
        Swap(5, 0.042),
        Swap(7, 0.044),
        Swap(10, 0.045),
    ]
    return bootstrap(market, monotone_cubic_zero())


# --------------------------------------------------------------------------- #
# The headline: exact fit (Hull-White) vs best fit (Vasicek / CIR)
# --------------------------------------------------------------------------- #


def test_hull_white_fits_exactly_where_vasicek_and_cir_leave_a_residual() -> None:
    """Hull--White reprices the curve to machine precision; Vasicek/CIR carry a real residual."""
    curve = _market_curve()
    pillars = curve.times

    hull_white = HullWhite.from_curve(curve, a=0.1, sigma=0.01)
    hw_error = float(
        np.max(np.abs(hull_white.discount_bond(pillars) - curve.discount_factor(pillars)))
    )
    vasicek = calibrate_vasicek(curve)
    cir = calibrate_cir(curve)

    assert hw_error < 1e-12  # exact by construction
    assert vasicek.rmse > 1e-4  # a genuine best-fit residual (> 1 bp), not exact
    assert cir.rmse > 1e-4
    # ... but the constant-parameter models still fit the shape to a few bps.
    assert vasicek.rmse < 30e-4
    assert cir.rmse < 30e-4


def test_known_truth_vasicek_curve_is_recovered() -> None:
    """A curve generated by a Vasicek model is recovered by Vasicek calibration to ~0 residual."""
    true = Vasicek(a=0.4, b=0.05, sigma=0.01, r0=0.03)
    times = np.array([0.25, 0.5, 1.0, 2.0, 3.0, 5.0, 7.0, 10.0])
    curve = DiscountCurve(times, np.asarray(true.discount_bond(times)), log_linear_discount())

    result = calibrate_vasicek(curve)
    assert result.rmse < 1e-6  # the model can fit its own curve essentially exactly
    fitted = result.model
    assert isinstance(fitted, Vasicek)
    assert abs(fitted.a - true.a) < 0.05  # and recovers the mean-reversion / level
    assert abs(fitted.b - true.b) < 0.01


def test_cir_calibration_exposes_feller() -> None:
    """The calibrated CIR model carries its Feller flag, and reprices the curve reasonably."""
    curve = _market_curve()
    result = calibrate_cir(curve)
    assert isinstance(result.model, CIR)
    assert isinstance(result.model.feller_satisfied, bool)
    assert result.max_abs_error < 40e-4  # largest pillar zero-rate error within a few bps
    assert result.n_pillars == curve.times.size
